--- !ditz.rubyforge.org,2008-03-06/issue 
title: Raise an exception on lack of arguments
desc: |-
  (: This code causes aborting :)
  def foo(bar)
    print(bar)
  end
  
  foo()
type: :task
component: core
release: 0.0.4
reporter: Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
status: :closed
disposition: :fixed
creation_time: 2009-12-31 02:47:59.625576 Z
references: []

id: cc00fdb4cb1e409fbe4b910a942f7cdbfb8b0dcc
log_events: 
- - 2009-12-31 02:48:00.532425 Z
  - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
  - created
  - ""
- - 2010-01-01 04:15:25.504346 Z
  - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
  - assigned to release 0.0.4 from unassigned
  - ""
- - 2010-01-10 03:05:48.540139 Z
  - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
  - changed status from unstarted to in_progress
  - ""
- - 2010-01-10 05:19:15.302614 Z
  - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
  - closed with disposition fixed
  - ""
